planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
  RRTkConfigDefault:
    type: geometric::RRT
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
  LazyRRTkConfigDefault:
    type: geometric::LazyRRT
  ESTkConfigDefault:
    type: geometric::EST
  KPIECEkConfigDefault:
    type: geometric::KPIECE
  RRTStarkConfigDefault:
    type: geometric::RRTstar
  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
  PRMkConfigDefault:
    type: geometric::PRM
  PRMStarkConfigDefault:
    type: geometric::PRMstar
  SafeRRTStarBasickConfigDefault:
    type: geometric::SafeRRTstarBasic
  SafeRRTStarkConfigDefault:
    type: geometric::SafeRRTstar
  SafePRMkConfigDefault:
    type: geometric::SafePRM
  CForestkConfigDefault:
    type: geometric::CForest
  SafeCForestkConfigDefault:
    type: geometric::SafeCForest
  SafeBiTRRTkConfigDefault:
    type: geometric::SafeBiTRRT
  SafeBiRRTStarkConfigDefault:
    type: geometric::SafeBiRRTstar
  BITStarkConfigDefault:
    type: geometric::BITstar
  SPARStwokConfigDefault:
    type: geometric::SPARStwo
  FMTkConfigDefault:
    type: geometric::FMT
  TRRTkConfigDefault:
    type: geometric::TRRT
  BiTRRTkConfigDefault:
    type: geometric::BiTRRT
left_arm:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - PRMkConfigDefault
    - PRMStarkConfigDefault
    - SafeRRTStarBasickConfigDefault
    - SafeRRTStarkConfigDefault
    - SafePRMkConfigDefault
    - CForestkConfigDefault
    - SafeCForestkConfigDefault
    - SafeBiTRRTkConfigDefault
    - SafeBiRRTStarkConfigDefault
    - BITStarkConfigDefault
    - SPARStwokConfigDefault
    - FMTkConfigDefault
    - TRRTkConfigDefault
    - BiTRRTkConfigDefault
  projection_evaluator: joints(left_s0,left_s1)
  longest_valid_segment_fraction: 0.05
right_arm:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - PRMkConfigDefault
    - PRMStarkConfigDefault
    - SafeRRTStarBasickConfigDefault
    - SafeRRTStarkConfigDefault
    - SafePRMkConfigDefault
    - CForestkConfigDefault
    - SafeCForestkConfigDefault
    - SafeBiTRRTkConfigDefault
    - SafeBiRRTStarkConfigDefault
    - BITStarkConfigDefault
    - SPARStwokConfigDefault
    - FMTkConfigDefault
    - TRRTkConfigDefault
    - BiTRRTkConfigDefault
  projection_evaluator: joints(right_s0,right_s1)
  longest_valid_segment_fraction: 0.01
both_arms:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - PRMkConfigDefault
    - PRMStarkConfigDefault
    - SafeRRTStarBasickConfigDefault
    - SafeRRTStarkConfigDefault
    - SafePRMkConfigDefault
    - CForestkConfigDefault
    - SafeCForestkConfigDefault
    - SafeBiTRRTkConfigDefault
    - SafeBiRRTStarkConfigDefault
    - BITStarkConfigDefault
    - SPARStwokConfigDefault
    - FMTkConfigDefault
    - TRRTkConfigDefault
    - BiTRRTkConfigDefault
  projection_evaluator: joints(right_s0,right_s1)
  longest_valid_segment_fraction: 0.05
left_hand:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - PRMkConfigDefault
    - PRMStarkConfigDefault
    - SafeRRTStarBasickConfigDefault
    - SafeRRTStarkConfigDefault
    - SafePRMkConfigDefault
    - CForestkConfigDefault
    - SafeCForestkConfigDefault
    - SafeBiTRRTkConfigDefault
    - SafeBiRRTStarkConfigDefault
    - BITStarkConfigDefault
    - SPARStwokConfigDefault
    - FMTkConfigDefault
    - TRRTkConfigDefault
    - BiTRRTkConfigDefault
right_hand:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - PRMkConfigDefault
    - PRMStarkConfigDefault
    - SafeRRTStarBasickConfigDefault
    - SafeRRTStarkConfigDefault
    - SafePRMkConfigDefault
    - CForestkConfigDefault
    - SafeCForestkConfigDefault
    - SafeBiTRRTkConfigDefault
    - SafeBiRRTStarkConfigDefault
    - BITStarkConfigDefault
    - SPARStwokConfigDefault
    - FMTkConfigDefault
    - TRRTkConfigDefault
    - BiTRRTkConfigDefault
