planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
  RRTkConfigDefault:
    type: geometric::RRT
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
  LazyRRTkConfigDefault:
    type: geometric::LazyRRT
  ESTkConfigDefault:
    type: geometric::EST
  KPIECEkConfigDefault:
    type: geometric::KPIECE
  RRTStarkConfigDefault:
    type: geometric::RRTstar
  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
  PRMkConfigDefault:
    type: geometric::PRM
  PRMStarkConfigDefault:
    type: geometric::PRMstar
  SafeRRTStarkConfigDefault:
    type: geometric::SafeRRTstar
  SafePRMkConfigDefault:
    type: geometric::SafePRM
  CForestkConfigDefault:
    type: geometric::CForest
  SafeCForestkConfigDefault:
    type: geometric::SafeCForest
  SafeBiTRRTkConfigDefault:
    type: geometric::SafeBiTRRT
  SafeBiRRTStarkConfigDefault:
    type: geometric::SafeBiRRTstar
left_arm:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - PRMkConfigDefault
    - PRMStarkConfigDefault
    - SafeRRTStarkConfigDefault
    - SafePRMkConfigDefault
    - CForestkConfigDefault
    - SafeCForestkConfigDefault
    - SafeBiTRRTkConfigDefault
    - SafeBiRRTStarkConfigDefault
  projection_evaluator: joints(left_s0,left_s1)
  longest_valid_segment_fraction: 0.05
right_arm:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - PRMkConfigDefault
    - PRMStarkConfigDefault
    - SafeRRTStarkConfigDefault
    - SafePRMkConfigDefault
    - CForestkConfigDefault
    - SafeCForestkConfigDefault
    - SafeBiTRRTkConfigDefault
    - SafeBiRRTStarkConfigDefault
  projection_evaluator: joints(right_s0,right_s1)
  longest_valid_segment_fraction: 0.05
both_arms:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - PRMkConfigDefault
    - PRMStarkConfigDefault
    - SafeRRTStarkConfigDefault
    - SafePRMkConfigDefault
    - CForestkConfigDefault
    - SafeCForestkConfigDefault
    - SafeBiTRRTkConfigDefault
    - SafeBiRRTStarkConfigDefault
  projection_evaluator: joints(right_s0,right_s1)
  longest_valid_segment_fraction: 0.05
left_hand:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - PRMkConfigDefault
    - PRMStarkConfigDefault
    - SafeRRTStarkConfigDefault
    - SafePRMkConfigDefault
    - CForestkConfigDefault
    - SafeCForestkConfigDefault
    - SafeBiTRRTkConfigDefault
    - SafeBiRRTStarkConfigDefault
right_hand:
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - PRMkConfigDefault
    - PRMStarkConfigDefault
    - SafeRRTStarkConfigDefault
    - SafePRMkConfigDefault
    - CForestkConfigDefault
    - SafeCForestkConfigDefault
    - SafeBiTRRTkConfigDefault
    - SafeBiRRTStarkConfigDefault
